# MongoDB Version 5.0 Docker
# docker-compose -f docker-compose.yml up -d

version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rsLP32A1rgbu
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
    networks:
      - monitor_net

networks:
  monitor_net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
